In [1]:
# importing libs necessary fro scraping bookings
from bs4 import BeautifulSoup
import requests

In [2]:
def extract(location):
  'Function that gets data from bookings.com and has location as an arguement whereby a location such as Nairobi or any other is passed to the function '
  
  headers = {'user_agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'}
  page_url = f'https://www.booking.com/city/ke/{location}.html'
  r = requests.get(page_url,headers)
  # make a beautifulsoup object
  soup = BeautifulSoup(r.content,'html.parser')
  return soup

In [3]:
def transform(soup):
  'This function takes the variable soup because its returning the soup from extract function and parsing it '
  divs = soup.find_all('div',class_ = 'sr__card')

  # looping all the hotel-cards with class = 'sr__card'
  for item in divs:

    # item in the divs that contains hotel name
    htl_name = item.find('span').text.strip()

    # item in the divs that contains price per night
    htl_price = item.find('div',class_ = 'bui-price-display__value').text.replace('$','')

    # item in the divs that contains the taotal number of reviews
    no_reviews = item.find('div',class_ = 'bui-review-score__text').text.strip().replace('reviews','')

    # item in the divs that contains the score of each hotel
    htl_score = item.find('div',class_ = 'bui-review-score__title').text.strip()

    # item in the divs that contains review type eg.Good,Excellent
    review_type = item.find('div',class_ = 'bui-review-score__title').text.strip()

    # item in the divs that contains the location
    htl_location = item.find('span',itemprop = 'addressLocality').text.strip()

    # item in the divs that contain score rating
    htl_rating = item.find('div',class_ = 'bui-review-score__badge').text.replace('\n','')
   
  # loading the data into a dictionary
    nai_hotels = {
        'hotel_name':htl_name,
        'location':htl_location,
        'reviews_count':no_reviews,
        'hotel_score':htl_score,
        'rating': htl_rating,
        'price':htl_price
     }
    nai_bookings.append(nai_hotels)
  return

In [4]:
# load hotel data and printing
nai_bookings = []
c = extract('nairobi')
transform(c)
print(len(nai_bookings))

10

In [5]:
# import pandas inorder to create a dataframe 
import pandas as pd

In [6]:
# loading to a dataframe
df = pd.DataFrame(nai_bookings)
# saving as a csv file
df.to_csv('bookingsnairobi.csv')

In [7]:
df.head(10)

,hotel_name,location,reviews_count,hotel_score,rating,price
0,"ibis Styles - Nairobi, Westlands","Hotel in Westlands, Nairobi","1,138",Good,7.7,62.10
1,"Crowne Plaza Nairobi Airport, an IHG Hotel",Hotel in Nairobi,"1,230",Excellent,8.7,138.24
2,Best Western Plus Meridian Hotel,"Hotel in Nairobi CBD, Nairobi","1,296",Very Good,8,68.06
3,Four Points by Sheraton Nairobi Airport,Hotel in Nairobi,889,Excellent,8.6,165
4,The Concord Hotel & Suites,Hotel in Nairobi,694,Very Good,8.1,125
5,Kahama Hotel Nairobi,Hotel in Nairobi,733,Good,7.6,20
6,254 Ole Sereni-Nairobi Park View,Hotel in Nairobi,696,Good,7.7,98
7,Best Western Plus Westlands,"Hotel in Westlands, Nairobi",746,Excellent,8.6,118.40
8,"Lotos Inn & Suites, Nairobi","Hotel in Westlands, Nairobi",924,Very Good,8,75
9,The Boma Nairobi,Hotel in Nairobi,613,Very Good,8.3,98.33